// Auto-generated testbench — do not edit by hand.
// Generated by gen_tb.py
//
// Formula: 4 clauses, 7 variables
// HW array: 4 clauses (padded to power-of-2)
// DPLL result: SAT
`timescale 1ns/1ps

module sat_submodule_tb;

    localparam VID_WIDTH   = 20;
    localparam NUM_CLAUSES = 4;
    localparam CID_WIDTH   = $clog2(NUM_CLAUSES);
    localparam NUM_ROWS    = 3 * NUM_CLAUSES;
    localparam ROW_ADDR_W  = $clog2(NUM_ROWS);

    localparam OP_IDLE     = 3'd0;
    localparam OP_LOAD     = 3'd1;
    localparam OP_BCP      = 3'd2;
    localparam OP_UNDO     = 3'd3;
    localparam OP_CIT_READ = 3'd4;

    localparam VAL_ZERO = 2'b00;
    localparam VAL_ONE  = 2'b01;
    localparam VAL_U    = 2'b10;

    logic                    clk, rst_n;
    logic [2:0]              op;
    logic                    phase;
    logic [VID_WIDTH-1:0]    vid_in;
    logic [1:0]              val_in;
    logic                    pol_in;
    logic [ROW_ADDR_W-1:0]   row_addr;
    logic [CID_WIDTH-1:0]    cid_in;

    logic                    conf_out, up_out, done_out;
    logic [CID_WIDTH-1:0]    cid_out;
    logic [1:0]              up_lit_pos;
    logic [VID_WIDTH-1:0]    vid_out;
    logic                    pol_out;
    logic                    valid_out;

    sat_submodule #(
        .VID_WIDTH  (VID_WIDTH),
        .NUM_CLAUSES(NUM_CLAUSES),
        .CID_WIDTH  (CID_WIDTH)
    ) dut (.*);

    initial clk = 0;
    always #5 clk = ~clk;

    // ── Cycle counters ───────────────────────────────────────────
    longint bcp_call_count   = 0;
    longint bcp_total_cycles = 0;
    longint undo_call_count  = 0;
    longint undo_total_cycles = 0;
    int     num_errors = 0;

    // ── Tasks ────────────────────────────────────────────────────
    task idle_cycle;
        op = OP_IDLE; vid_in = '0; val_in = '0; pol_in = '0;
        row_addr = '0; cid_in = '0; phase = '0;
        @(posedge clk); #1;
    endtask

    task load_row(input int                     raddr,
                  input logic [VID_WIDTH-1:0]   vid,
                  input logic                   pol);
        op = OP_LOAD; row_addr = raddr; vid_in = vid;
        pol_in = pol; val_in = VAL_U; phase = '0; cid_in = '0;
        @(posedge clk); #1;
        op = OP_IDLE;
        @(posedge clk); #1;
    endtask

    task bcp(input logic [VID_WIDTH-1:0] vid,
             input logic [1:0]            val);
        longint t_start;
        t_start = $time / 10;
        op = OP_BCP; vid_in = vid; val_in = val;
        phase = 0; row_addr = '0; pol_in = '0; cid_in = '0;
        @(posedge clk); #1;
        @(posedge clk); #1;
        op = OP_IDLE;
        bcp_total_cycles += ($time / 10) - t_start;
        bcp_call_count++;
    endtask

    task undo(input logic [VID_WIDTH-1:0] vid);
        longint t_start;
        t_start = $time / 10;
        op = OP_UNDO; vid_in = vid; val_in = VAL_U;
        phase = 0; row_addr = '0; pol_in = '0; cid_in = '0;
        @(posedge clk); #1;
        op = OP_IDLE;
        @(posedge clk); #1;
        undo_total_cycles += ($time / 10) - t_start;
        undo_call_count++;
    endtask

    task check(input string name,
               input logic exp_conf, exp_up, exp_done);
        if (conf_out !== exp_conf || up_out !== exp_up || done_out !== exp_done) begin
            $display("FAIL [%s]: conf=%b up=%b done=%b  expected conf=%b up=%b done=%b",
                     name, conf_out, up_out, done_out,
                     exp_conf, exp_up, exp_done);
            num_errors++;
        end else begin
            $display("PASS [%s]: conf=%b up=%b done=%b",
                     name, conf_out, up_out, done_out);
        end
    endtask

    // check() variant for UNDO (same logic, separate name for clarity)
    task check_undo(input string name,
                    input logic exp_conf, exp_up, exp_done);
        check(name, exp_conf, exp_up, exp_done);
    endtask

    initial begin
        $vcdplusfile("waves.vpd");
        $vcdpluson;

        // Reset
        rst_n = 0; op = OP_IDLE; vid_in = '0; val_in = '0;
        pol_in = '0; row_addr = '0; cid_in = '0; phase = '0;
        repeat(2) @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // ── LOAD ────────────────────────────────────────────────
        $display("\n-- LOAD --");
        // Clause 0
        load_row(  0, 20'd1, 1'b0);  // C0 L0: x1  (pos)
        load_row(  1, 20'd2, 1'b0);  // C0 L1: x2  (pos)
        load_row(  2, 20'd6, 1'b1);  // C0 L2: ~x6  (neg)

        // Clause 1
        load_row(  3, 20'd2, 1'b0);  // C1 L0: x2  (pos)
        load_row(  4, 20'd3, 1'b1);  // C1 L1: ~x3  (neg)
        load_row(  5, 20'd6, 1'b0);  // C1 L2: x6  (pos)

        // Clause 2
        load_row(  6, 20'd1, 1'b1);  // C2 L0: ~x1  (neg)
        load_row(  7, 20'd3, 1'b0);  // C2 L1: x3  (pos)
        load_row(  8, 20'd4, 1'b0);  // C2 L2: x4  (pos)

        // Clause 3
        load_row(  9, 20'd2, 1'b1);  // C3 L0: ~x2  (neg)
        load_row( 10, 20'd4, 1'b1);  // C3 L1: ~x4  (neg)
        load_row( 11, 20'd5, 1'b0);  // C3 L2: x5  (pos)

        $display("\n-- SOLVE (Python DPLL result: SAT) --");
        bcp(20'd1, VAL_ONE);
        check("DEC(x1=1)", 1'b0, 1'b0, 1'b0);

        bcp(20'd2, VAL_ONE);
        check("DEC(x2=1)", 1'b0, 1'b0, 1'b0);

        bcp(20'd3, VAL_ONE);
        check("DEC(x3=1)", 1'b0, 1'b0, 1'b0);

        bcp(20'd4, VAL_ONE);
        check("DEC(x4=1)", 1'b0, 1'b1, 1'b0);

        bcp(20'd5, VAL_ONE);
        check("DEC(x5=1)", 1'b0, 1'b0, 1'b1);

        // ── STATS ────────────────────────────────────────────────
        $display("\n-- DONE --");
        $display("BCP_STATS: bcp_calls=%0d bcp_cycles=%0d undo_calls=%0d undo_cycles=%0d",
                 bcp_call_count, bcp_total_cycles,
                 undo_call_count, undo_total_cycles);
        if (num_errors == 0)
            $display("ALL TESTS PASSED");
        else
            $display("FINISHED WITH %0d ERROR(S)", num_errors);

        $vcdplusoff;
        $finish;
    end

endmodule
